name: Provents
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  http: ^1.3.0
  multicast_dns: ^0.3.3
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  fl_chart: ^0.71.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
